[package]
name = "rock_paper_scissors"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"

[dev-dependencies]
snforge_std = "0.31.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test" 